version: '3.8'
services:
  nginx:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - URL=hnjobs.cncf.io
      - VALIDATION=http
    volumes:
      - ./config/nginx:/config/nginx/site-confs
      - ./public:/config/www
      - ./log:/config/log
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
