version: '3.8'
services:
  app:
    command: "rerun -d lib -b 'ruby lib/generate_files.rb'"
  caddy:
    image: caddy
    ports:
      - 8000:80
    container_name: caddy
    volumes:
      - ./public:/usr/share/caddy
      - ./caddy_data:/data
    restart: unless-stopped
